### ISSUE TITLE
Any examples/tutorials for preparing input files from gromacs/openmm ?

### ISSUE THREAD

**Issue by Zhaoyang-XU** [ProLint/ProLint#16]
Hi, 

I have problems converting my gromacs MD output to the formats required for Prolint input. Is there any example/tutorials demonstrating how to do it properly?Thanks!
All the best,
John

**Comment by bisejdiu** [comment]
Hi John, 

I'm assuming you are referring to removing water and ion atoms/beads from the system? There are plenty of gromacs tutorials online on how to do trajectory preprocessing, but basically, you want to look at the `gmx trjconv` command and supply to it an index file that contains the protein and lipid groups. 

[For example](https://manual.gromacs.org/documentation/5.1/onlinehelp/gmx-trjconv.html)

**Comment by Zhaoyang-XU** [comment]
Hi Bisejdiu,
Thanks a lot.  I’ve figure that out  now. Still, a full tutorial would be very useful.
Regards,
John
